### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by harukou81mmm** [harukou81mmm/furima-36344#21]
＃URL
https://furima-36344.herokuapp.com/

＃Basic認証のIDとパスワード
    ID.       : admin
    PW.     : 2222

＃出品者用のメールアドレスとパスワード
アドレス：sample20@sample.com
  　PW   ：yuuuna20

＃購入者用のメールアドレスとパスワード
アドレス：sample50@sample.com
  　PW   ：satou12345

**Comment by miyu-yamamoto** [comment]
@harukou81mmm さん、お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]

**商品出品機能**

- [x] **エラーハンドリングの際、1つのエラーに対して同じエラーメッセージが重複して表示されないこと**
価格を未入力の状態で「出品する」ボタンを押すと、重複したエラーが表示されます
<img width="412" alt="スクリーンショット 2021-12-22 10 10 34" src="https://user-images.githubusercontent.com/59544869/147018090-2badb116-caf8-4949-bbfe-4c6594c683b2.png">

**商品編集機能**

- [x] **エラーハンドリングの際、1つのエラーに対して同じエラーメッセージが重複して表示されないこと**
価格を未入力の状態で「変更する」ボタンを押すと、重複したエラーが表示されます
<img width="412" alt="スクリーンショット 2021-12-22 10 10 34" src="https://user-images.githubusercontent.com/59544869/147018377-f9e04edc-9fe6-4464-a011-e9505dbbc838.png">

**商品購入機能**

- [x] **クレジットカード情報は必須であり、下記のPAY.JPテストカードの情報で決済ができること**
```
・カード番号：4242424242424242
・有効期限：今日より未来の日付
・セキュリティコード：123
```
正しいカード情報を入力しても、エラーが表示され購入が完了できません
<img width="233" alt="スクリーンショット 2021-12-22 10 19 27" src="https://user-images.githubusercontent.com/59544869/147018815-0d44c1db-d451-4406-af01-47b6f5f3e687.png">
※上記により、購入後の機能は今回確認できておりません

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by harukou81mmm** [comment]
ご確認いただきましてありがとうございます！
修正完了しましたが、
”クレジットカード情報は必須であり、下記のPAY.JPテストカードの情報で決済ができること”につきまして
ローカルでは正常通り購入ができるのですが、heroku上ではエラーが起こってしまいます。

カリキュラムを参考に以下の確認を行いました。
・環境変数設定されているか
・空コミットしてからherokuへプッシュ
https://gyazo.com/720011f9622e66e71934b0ade5f4c0bb
やはり解決せず。
また、・heroku logs --tail --appを実行して以下のログを見たのですが、ピンとこず…
https://gyazo.com/b92c3c0a599b958962f9e07af643df0e

何か足りない手順がございますでしょうか。ご教示のほどよろしくお願い致します。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x]  **クレジットカード情報は必須であり、下記のPAY.JPテストカードの情報で決済ができること**
```
・カード番号：4242424242424242
・有効期限：今日より未来の日付
・セキュリティコード：123
```
正しいカード情報を入力しても、「Token can't be blank」というエラーが表示され購入が完了できません。

※恐れ入りますが、技術的なご質問に関してはこちらでお答えすることが出来かねます。
デプロイ関係でご不明点がございましたらテックコネクトにてご相談をお願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by harukou81mmm** [comment]
修正完了しました。ご確認の程よろしくお願い致します。

＃URL
https://furima-36344.herokuapp.com/

＃Basic認証のIDとパスワード
ID. : admin
PW. : 2222

＃出品者用のメールアドレスとパスワード
アドレス：sample20@sample.com
　PW ：yuuuna20

＃購入者用のメールアドレスとパスワード
アドレス：sample50@sample.com
　PW ：satou12345

**Comment by miyu-yamamoto** [comment]
@harukou81mmm さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6853

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題LGTM](https://user-images.githubusercontent.com/59544869/147169638-81ee7e9b-f8e4-4843-9b03-01706a566164.png)
